list: $/luismayta/intranet/models/material/columns.yaml
modelClass: LuisMayta\Intranet\Models\Material
title: Material
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/intranet/material/update/:id'
