list: $/luismayta/intranet/models/descargas/columns.yaml
modelClass: LuisMayta\Intranet\Models\Descargas
title: Descargas
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/intranet/descargas/update/:id'
