list: $/luismayta/intranet/models/registro/columns.yaml
modelClass: LuisMayta\Intranet\Models\Registro
title: Registro
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/intranet/registro/update/:id'
