list: $/luismayta/intranet/models/biografia/columns.yaml
modelClass: LuisMayta\Intranet\Models\Biografia
title: Biografia
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/intranet/biografia/update/:id'
