list: $/luismayta/intranet/models/blog/columns.yaml
modelClass: LuisMayta\Intranet\Models\Blog
title: Blog
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/intranet/blog/update/:id'
