list: $/luismayta/intranet/models/banner/columns.yaml
modelClass: LuisMayta\Intranet\Models\Banner
title: Banner
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/intranet/banner/update/:id'
