list: $/luismayta/intranet/models/cursosvirtuales/columns.yaml
modelClass: LuisMayta\Intranet\Models\CursosVirtuales
title: CursosController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/intranet/cursoscontroller/update/:id'
