list: $/luismayta/intranet/models/usercurso/columns.yaml
modelClass: LuisMayta\Intranet\Models\UserCurso
title: UserCurso
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'luismayta/intranet/usercurso/update/:id'
